apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchx-ide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launchx-ide
  template:
    metadata:
      labels:
        app: launchx-ide
    spec:
      containers:
        - name: launchx-ide
          image: gcr.io/launchx-jc/launchx-ide:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: WS_PATH
              value: "wss://launchx.studio"
          volumeMounts:
          - mountPath: /workspace
            name: workspace-volume

          
      volumes:
      - name: workspace-volume
        persistentVolumeClaim:
          claimName: workspace-pvc
   